ListItemTable:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: "${self:custom.dynamoDBTableName}"
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: lastModified
        AttributeType: N
    KeySchema:
      - AttributeName: id
        KeyType: "HASH"
      - AttributeName: lastModified
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1

AppSyncDynamoDBServiceRole:
  Type: "AWS::IAM::Role"
  Properties:
    RoleName: ${self:custom.role.dynamodb.name}
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - 
          Effect: "Allow"
          Principal:
            Service:
              - "appsync.amazonaws.com"
          Action:
            - "sts:AssumeRole"
    Policies:
      -
        PolicyName: ${self:custom.role.dynamodb.name}-Policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - 
              Effect: "Allow"
              Action:
                - "dynamodb:Query"
                - "dynamodb:BatchWriteItem"
                - "dynamodb:GetItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:PutItem"
                - "dynamodb:UpdateItem"
                - "dynamodb:BatchGetItem"
              Resource:
                - "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.dynamoDBTableName}"
                - "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.dynamoDBTableName}/*"
      